package rpc_protocol;

public enum AnswerType {
    OK,
    ERROR,
    FULL_SHOW_LIST,
    FULL_SHOW_LIST_DYNAMIC_UPDATE,  // UNREQUESTED BY CLIENTS
    FILTERED_SHOW_LIST,
    FILTERED_SHOW_LIST_DYNAMIC_UPDATE   // UNREQUESTED BY CLIENTS
}
